### ISSUE TITLE
Little documentation on how to use this component

### ISSUE THREAD

**Issue by jackmatt2** [paddle8/ember-plupload#1]
I am trying to use this plugin to get somethign like (http://www.plupload.com/examples).  It appears that no styles are shipped with this ... is that correct?  I am also unsure of how to get drag and drop working or even a submit button working.

Here is my code so far:

```javascript
{{#pl-uploader action="http://localhost:8085/upload" for="my-browse-button" name="test" extensions="doc jpg pdf png" no-duplicates=true}}
    <h4>Upload documents</h4>
    <button type="button" id="my-browse-button">Add Files</button>
    <button type="submit">Upload</button>
{{/pl-uploader}}
```

Pressing the "Add Files" button seems to load the file selection dialog but when I select one nothing appears to happen.  Clicking the submit button does not appear to do anything at all.

**Comment by tim-evans** [comment]
@jackmatt2 sorry for the very late response.

I'm working on simplifying this component and adding tests, since this was causing spaghetti code throughout our app. Keep an eye out, as I'll be trying to ameliorate API issues that are making things difficult here.

**Comment by IanVS** [comment]
I attempted to use this addon based on the example given in the readme, and failed miserably.  I could see that something was being added to the DOM, but it was all invisible for some reason.  Do you have any other examples or blog posts you can share about how to use this?  It looks promising but unfortunately I just can't figure it out.

**Comment by tim-evans** [comment]
@IanVS could you provide some information on what version of ember you're using and the hbs that you've used in your app, along with any configuration variables? Thanks

**Comment by IanVS** [comment]
Yes I can do that tonight via a separate issue, but my intent here was not necessarily for help debugging my specific issue, as I can't tell if I'm using it correctly or not.  I was mostly asking if there are any demos you can point to, or further information on how to use this addon.  Am I correct in thinking this component should just be able to be added to a template containing an upload button (and linked to it's id via "for")?  Do any actions need to be set in that upload button?  Does the upload button need to be placed inside the {{#pl-uploader}} component, or can it live elsewhere?  It is these kinds of basic questions that I am struggling with understanding, and a complete working example would go a long way in helping me to understand.

**Comment by tim-evans** [comment]
Ahh, the docs use `{{with}}`, which breaks the demo. I'll add a sample to the dummy folder in tests and update the docs

**Comment by tim-evans** [comment]
@IanVS as for the button, yes. It can be an element outside of the pl-upload component block.

The only action that needs to be set is the `when-queued` property.
