### ISSUE TITLE
Ember CLI 0.2.3 Installation

### ISSUE THREAD

**Issue by timohofmeijer** [paddle8/ember-plupload#11]
I’m having some issues when installing this addon in an `ember-cli 0.2.3` app.

The updated syntax for installing an addon should be:
```
ember install ember-plupload
```
Next it throws the following error:
```
The `ember generate` command requires an entity name to be specified. For more details, use `ember help`.
```

**Comment by tim-evans** [comment]
Yeah, I've seen this. Not sure what's going on here... Might want to raise this in ember-cli/ember-cli

**Comment by IanVS** [comment]
It is a known issue in ember-cli (https://github.com/ember-cli/ember-cli/issues/3831), and is only a warning.  Looks like it was just now closed by https://github.com/ember-cli/ember-cli/issues/3831

**Comment by tim-evans** [comment]
@IanVS hooray! Thanks for resolving this for me :)

**Comment by timohofmeijer** [comment]
Many thanks!
