### ISSUE TITLE
html4 runtime does not seems to work

### ISSUE THREAD

**Issue by AdrienNguyenWorldline** [paddle8/ember-plupload#17]
I need to be able to run with HTML4 runtime for IE9 compatibility.

But if I try an uploader with `runtimes="html4"` only, nothing happends when I click on the mapped button (no file selection UI and no error message).

Do you have a setup that works with html4 runtime (in either browser).

On plupload test page, I see that there is a hidden div behind the button with a file input.
but I can't find it on my page.

I manually tested finding the div with a jquery selector : `$(".moxie-shim-html4")` which worked on http://plupload.com/examples/runtimes but found nothing on my page

here is my handlebar
```
{{#pl-uploader extensions="pdf doc docx xls xlsx ppt pptx" runtimes="html4" for="newDoc" when-queued="uploadDoc" max-file-size="1024kb" as |queue features|}}
<a id="newDoc" class="btn btn-primary">{{format-message (intl-get 'documents.browse')}}</a><br/>
{{/pl-uploader}}```

**Comment by tim-evans** [comment]
Geez, this is a tough one for me to test. I don't have an IE machine on hand. If you could dig in and provide more details, that'd be super helpful

**Comment by AdrienNguyenWorldline** [comment]
I don't either, we are testing with a modernIE running IE9 Win7 virtual machine (http://dev.modern.ie/tools/vms/).
But the bug is the same running chrome on Win7 if I disable the other runtimes changing `runtimes="html5,flash,html4"` to `runtimes="html4"`.

**Comment by tim-evans** [comment]
Ok- sounds like a good starting point. I'll enable html4 only and start going from there when I have some time.

**Comment by tim-evans** [comment]
It seems I was overeager in adding `required_features: true` in the plupload config :flushed:
