### ISSUE TITLE
Multiple file upload failing when file plupload settings not set before file upload started

### ISSUE THREAD

**Issue by walter** [paddle8/ember-plupload#22]
### Background

My app gets a S3 pre-signed upload URL from an API set up to do authorization before returning the URL. Sometimes this takes multiple tries to get authorization with a set delay between each retry due to the idiosyncrasies of our authorization rules. 

As you may remember, I use slightly customized version of plupload to support the PUT method. Here's the branch with the modifications [for reference](https://github.com/lytbulb/plupload/tree/s3-required-modifications).

On this set up single uploads, ember-plupload (0.6.18) works reliably. The file specific settings (put method, url, content type header) are set correctly.

### The Problem

However, sometimes with multiple file uploads the file specific settings fail to be passed to plupload (I have verified this with logging in my app, ember-plupload, and in plupload) and the file upload starts with the default settings which then fails with `DOMException 12` because the URL is not present.

I tracked down the issue to be due to the timing in this line:

https://github.com/paddle8/ember-plupload/blob/master/addon/system/file.js#L154

If I up the number from 100 to 400 my multiple file uploads that were previously failing work reliably and I have verified that the settings in line 151 are indeed used by plupload whereas at 100 they we not being used by plupload.

I must admit to being confused by why the settings taking effect is left to a matter of timing or even where the asynchronous failing of setting the settings in time is happening!

### The Solution?

Rather than up the number to 400 (which would slow uploads down per file, of course), I'm wondering if we can somehow make sure that the settings are in place for plupload before proceeding with starting the uploader. Any ideas?

Happy to talk through this on Skype or the like if that helps.

**Comment by walter** [comment]
cc @opsb

**Comment by tim-evans** [comment]
I believe the best approach here is to literally pass the settings through in that method. I'm out of town this weekend, but I'll be on this when I'm back

**Comment by walter** [comment]
Thanks for following up.

Ok, sounds good about passing the settings. I'll experiment while a bit on my Monday while I wait for your Monday.

**Comment by tim-evans** [comment]
I looked at this, and it seems like a longer delay is the easiest solution. Check out 0.6.21 to see if that works for you :)

**Comment by opsb** [comment]
@tim-evans your comment at https://github.com/paddle8/ember-plupload/blob/master/addon/system/file.js#L158 seems to imply that there's a newer version of plupload that includes the settings as part of the upload process. I couldn't find any mention of this in the plupload docs, you got a link?

**Comment by walter** [comment]
Upgraded to 0.6.21, unfortunately 300 isn't sufficient to fix my problem scenario. At least not in development mode.

I guess one possibility is to make the amount of the delay variable depending on a setting.

I took a look at some of the plupload internals as well as trying to simply update the assigned value of uploader.settings. Doing that seemed to kill things. uploader.setOption seemed to be the API for it, but that seems expensive, too.

**Comment by tim-evans** [comment]
@opsb master of plupload does this. See https://github.com/moxiecode/plupload/blob/master/src/plupload.js#L2123

**Comment by tim-evans** [comment]
And @walter can I get some browser information for debugging? This seems like a super annoying race condition that requires setting the uploader settings at the exact right time.

**Comment by opsb** [comment]
@tim-evans ah, that looks much better, definitely the way forwards then.

**Comment by tim-evans** [comment]
@opsb Unfortunately, I don't think it's ready for production yet :(

**Comment by opsb** [comment]
@tim-evans sure, I mean living with a delay temporarily is much more palatable if there's a better solution on the horizon.

**Comment by walter** [comment]
> And @walter can I get some browser information for debugging? This seems like a super annoying race condition that requires setting the uploader settings at the exact right time.

Yes, it is! Chrome 43.0.2357.81, with Ember 1.11.3. With the inspector open, of course. Yeah, I'm annoyed that a number that was previously working now doesn't seem to be sufficient.

I think I'll experiment with uploader.setOption a bit and get back to you.

**Comment by walter** [comment]
No love with using uploader.setOption directly as a test. I did it for a couple key settings to test if it would work in this context and it didn't flow through to the start call in pluploader that I can could see.

I'm inclined to simply fork ember-plupload so that we can tweak the delay to match our needs until plupload releases their update, etc.

No reason to penalize everyone else's upload speed so we can handle our case.

**Comment by walter** [comment]
Ok, here's our fork with the change that looks to solve the reliability problems we've had when there are three or more (medium sized) files being uploaded without slowing down single file uploads.

https://github.com/lytbulb/ember-plupload/commit/0b14068d202f2c44d88fca0964e90d556483abb1

Will report back if we make any adjustments.

**Comment by tim-evans** [comment]
Good to hear!

I took a look at your version of plupload, and it seems to be in-between the published version and the one with parallel uploads. I think your issues are arising with plupload, not the addon. I'll ping you on slack later if you'd like to run through this a bit more

**Comment by walter** [comment]
Thanks for looking into it more @tim-evans. Yes, let's touch base on slack. Will DM there to arrange a time.

**Comment by tim-evans** [comment]
Sorry, I'll get in touch tomorrow. There's an offsite today

**Comment by walter** [comment]
> I took a look at your version of plupload, and it seems to be in-between the published version and the one with parallel uploads. I think your issues are arising with plupload, not the addon.

You are correct, we are using a plupload fork that is based on plupload master after parallel uploading has been added to it. After your comment, I experimented with applying our changes to the 2.1.x branch of plupload. I still had the same issue.

However, since everything else with ember-plupload seems to be in good working order when using plupload with parallel uploading support, I decided to see if I could get things working with the new API.

And it worked great!

The result can be seen here:

https://github.com/lytbulb/ember-plupload/commit/d3a015b0588c63179086e629f661c342df1c46db

**Comment by tim-evans** [comment]
@walter that looks exactly right ;)

**Comment by tim-evans** [comment]
I cherry-picked the commit and it's in 0.6.22

**Comment by walter** [comment]
Thanks @tim-evans! 

Writing the test has been on my todo list, but I've kept pushing it back due to other deadlines. Appreciate you following up.

**Comment by tim-evans** [comment]
No problemo!

**Comment by tim-evans** [comment]
And I got the test written for it too :wink:
