### ISSUE TITLE
Multiple components issue

### ISSUE THREAD

**Issue by trampos** [paddle8/ember-plupload#24]
If i put 2 {{pl-uploader}} on the same route then i set distinct 'when-queued' for each, i can't make them call different route actions, they always call the 'when-queued' action related to the last added pl-uploader.

**Comment by tim-evans** [comment]
Could you write a test for this? If not, I can do that. I've definitely used multiple instances in a single route.

Could you also add the basic template to help me debug this?

**Comment by trampos** [comment]
I don't know how to write you a test for this, but my code is simple, i am trying to render 2 distinct pl-uploaders, but both call the same action. 

the code:

{{#pl-uploader for="upload-curriculum" multiple=false unique-names=true extensions="jpg jpeg png gif" when-queued="uploadCurriculum" as |queue dropzone|}}
<a id="upload-curriculum">Add an Curriculum.</a>
{{/pl-uploader}}
			
{{#pl-uploader for="upload-portfolio" multiple=false unique-names=true extensions="jpg jpeg png gif" when-queued="uploadPortfolio" as |queue dropzone|}}
<a id="upload-portfolio">Add an Portfolio.</a>
{{/pl-uploader}}

**Comment by tim-evans** [comment]
Hmm. Where's the browse button id for 'upload-portfolio' and 'upload-curriculum'.

**Comment by trampos** [comment]
its gone when i pasted it, but i found what i was doing wrong, i missed the line where u say "To use the uploader, you must provide a name (for proper queueing and bundling of resources), and an upload URL." i ve just copied & pasted the readme component code that has no name attr. Now with name set its working as expected, sry for that.

**Comment by tim-evans** [comment]
No problem :) Glad you fixed it.

This seems like a documentation issue, I think. I'll emphasize this in the README

**Comment by AdrienNguyenWorldline** [comment]
Nice too see, I did resolved to a trick having a single pl-uploader on the same page but 3 buttons setting a value to a variable then triggering the single plupload instance.

I should look at addind names too.
