### ISSUE TITLE
[Feature Request] support error handling like `when-queued`

### ISSUE THREAD

**Issue by efx** [paddle8/ember-plupload#26]
Thanks for putting together this plugin; it is working well.
I am running into an issue regarding how to retry an upload an errors from my upload endpoint.
Take the following workflow:
 1.  a user drags a file to the uploader 
 2.  the upload handler on my route fires
 3.  if that handler's promise rejects, I display an error message to the user 
  * depending on the error, I want to give the option to rename the file and resubmit the uploader

Right now, there doesn't seem to be a way to handle this workflow cleanly.
I have a hacked around the problem using plupload's API to programmatically modify the upload queue, but in doing so I am losing the file's content in the upload form. It would be nice to be able to resubmit the errored requests as an action on `{{plupload}}` so I can keep the state of the existing file and not have to have the user redrag the file again.

**Comment by tim-evans** [comment]
Would having the ability to call `upload` on a rejected file, having it be requeued work?

**Comment by efx** [comment]
yes that would. Whatever way I can cleanly retry a failed upload per file will resolve this use case. I am not attached to the 'on-error' idea, just thought of it as a starting point.
Is `upload` the ember-plupload's wrapper around plupload's file object?

**Comment by tim-evans** [comment]
The file being passed is the wrapper around the object. The `upload` method is an abstraction of the file's upload process.

**Comment by tim-evans** [comment]
@efx I added an onerror hook to 0.8.0. Not sure if that helps at all.

**Comment by efx** [comment]
Thanks Tim! I'll try this out when I get a moment.

**Comment by tim-evans** [comment]
I added file retries for 1.13.0. Hopefully it will work well for you.
