### ISSUE TITLE
upload on ie9 with html4 runtime

### ISSUE THREAD

**Issue by mgrigis** [paddle8/ember-plupload#29]
I have some problem with ie9 compatibility, sometime this work fine but sometime any api call is done (i check all request in network  tab).
It usually appears when i refresh the page with F5.

However it work fine in FF and Chrome.

my handlebar
```javascript 
{{#pl-uploader extensions=formats runtimes="html4" for="newDoc" when-queued="uploadDoc" max-file-size=maxSizeas as |queue dropzone|}}
        <a class="btn btn-primary" title="{{format-message (intl-get 'common.browse')}}" id="newDoc">{{format-message (intl-get 'common.browse')}}</a>
      {{/pl-uploader}}
```

with an uploadDoc callback function that manages the upload trigger via a file.upload() promise.

Do you have some idea ?

**Comment by mgrigis** [comment]
i found a solution, i replace 1 line in file.js and all work fine in ie9

i'm in 0.6.21
later(uploader, 'start', 400); -> uploader.start();

i wil test replacing this
later(uploader, 'start', 100); -> uploader.start();
in 0.6.22 version

what do you think about this ?

**Comment by tim-evans** [comment]
@_@ Ugh. I do not like race conditions. I'll patch and push a new version, noting this PR. At the latest, it will be done sometime around 7-8pm today EST.

**Comment by mgrigis** [comment]
ok thank you

**Comment by mgrigis** [comment]
The problem still exist with 0.8.0 version. More you increase the time less the bug appears (but still appears some times).

**Comment by mgrigis** [comment]
Bug still exist. I try to increase the value (not sufficient). The only way i found is to call directly uploader.start() and all work fine.

**Comment by tim-evans** [comment]
I think I may have fixed this with 0.8.1

**Comment by mgrigis** [comment]
it works with 0.8.1 
thank you

**Comment by tim-evans** [comment]
phew, thanks!
