### ISSUE TITLE
file size on IE9

### ISSUE THREAD

**Issue by mgrigis** [paddle8/ember-plupload#30]
Hi,
I got a problem in IE9 when i upload a doc, i call a callback method (UploadDoc) with a pluploadFile parameter. However size attributer is not defined (file.file.size, see that in screen). 

In all other browser (FF, Chrome, IE10, IE11) size attribute is present.

![plupload_file_size](https://cloud.githubusercontent.com/assets/3017497/8543114/dc974cbc-249a-11e5-8678-637587094f79.png)

This is my handlebars : 
```javascript

{{#pl-uploader name="docUploader" class="doc-uploader" extensions="pdf doc docx xls xlsx ppt pptx" runtimes="html4 flash" for="newDoc" when-queued="uploadDoc" max-file-size="10240kb" as |queue dropzone|}}
    <a class="btn btn-primary" title="browse" id="newDoc">browse</a>
{{/pl-uploader}}
```

**Comment by mgrigis** [comment]
it s not supporrted in plupload, i think that we couldn't do anything for this (i will patch my app in order to calculate size on server side)

**Comment by tim-evans** [comment]
Yeah. Sorry :<

Uploads are still painful without html5

**Comment by mgrigis** [comment]
Can be closed
