### ISSUE TITLE
can't upload files

### ISSUE THREAD

**Issue by tmayr** [paddle8/ember-plupload#32]
I just upgraded from 0.8.1 to 1.13.0 and when adding a file, the when-queued action doesn't trigger, no error in console or any trace of what might be going on.

Any idea on what could be causing this?, running pretty much the example from the readme.

**Comment by PowerP** [comment]
+1 , same here

**Comment by jchamet** [comment]
I am experiencing the bug as well. Upload status stays at 0% and my controller action is never called.

ember -v
version: 1.13.1
node: 0.12.2
npm: 2.12.1

Template
```
{{#pl-uploader for="upload-image" extensions="jpg jpeg png gif" when-queued="uploadImage" as |queue dropzone|}}
<div class="dropzone" id={{dropzone.id}}>
  {{#if dropzone.active}}
  {{#if dropzone.valid}}
  Drop to upload
  {{else}}
  Invalid
  {{/if}}
  {{else if queue.length}}
  Uploading {{queue.length}} files. ({{queue.progress}}%)
  {{else}}
  <h4>Upload Logo</h4>
  <p>
  {{#if dropzone.enabled}}
  Drag and drop image onto this area to upload it or
  {{/if}}
  <a id="upload-image">click here to add an image.</a>
  </p>
  {{/if}}
</div>
{{/pl-uploader}}
```

**Comment by tim-evans** [comment]
Not a bug. Read the changelog. Use 'onfileadd'.
