### ISSUE TITLE
A Different error on install

### ISSUE THREAD

**Issue by deathbearbrown** [paddle8/ember-plupload#34]
Here's the error I get when running `ember install ember-plupload`:

```
Installing browser packages via Bower...
  not-cached git://github.com/moxiecode/plupload.git#2.1.3=plupload#2.1.3#
Tag/branch 2.1.3=plupload#2.1.3# does not exist
Error: Tag/branch 2.1.3=plupload#2.1.3# does not exist
```

https://github.com/paddle8/ember-plupload/blob/master/blueprints/ember-plupload/index.js#L6

This needs to be changed to  `addBowerPackageToProject('plupload', '2.1.3');`

Because of this: https://github.com/ember-cli/ember-cli/pull/4643

**Comment by tim-evans** [comment]
Thanks for this! I just bumped plupload's dependency as well. I'll merge this in and note that it needs support for newer versions of ember-cli
