### ISSUE TITLE
Compatibility with ember-cli-materialize button components

### ISSUE THREAD

**Issue by IanVS** [paddle8/ember-plupload#5]
I am able to achieve full functionality with the template code given in the readme, but swapping out 

```
<a id="upload-image">Add an Image.</a>
```

with 
```
{{md-btn text='Upload Image' id='upload-image'}}
```

causes the browse box to no longer appear.  Is this due to an incompatibility with ember-cli-materialize, perhaps?  It doesn't seem to be the fact that it's a component, as I've been able to create a custom component and the upload still works fine.

**Comment by tim-evans** [comment]
I just bootsrapped a new app with the following code in a template:

```handlebars
{{#pl-uploader extensions="jpg jpeg png gif" action="/api/images/upload" for="u\
pload-image" when-queued="uploadImage" as |queue features|}}
<div class="dropzone" id={{features.drag-and-drop.dropzone-id}}>
  {{#if features.drag-and-drop.drag-data}}
    {{#if features.drag-and-drop.drag-data.valid}}
      Drop to upload
      {{else}}
      Invalid
    {{/if}}
    {{else if queue.length}}
    Uploading {{queue.length}} files. ({{queue.progress}}%)
    {{else}}
    <h4>Upload Images</h4>
    <p>
      {{#if features.drag-and-drop}}
        Drag and drop images onto this area to upload them or
      {{/if}}
      {{md-btn text="Add an Image." id="upload-image"}}
    </p>
  {{/if}}
</div>
{{/pl-uploader}}
```

And there isn't any problems. Please try to isolate your test cases before reporting :3 Thanks!

**Comment by IanVS** [comment]
I've determined this is a browser compatibility issue.  I did the same as you and created a new app, still with no success.  Then I tried using Firefox, and it works correctly.  Apparently Chromium 41 does not like something with the combination of materialize and plupload.  I don't have enough experience with browsers to take even the first steps towards figuring out why.
