### ISSUE TITLE
Show image preview after queued

### ISSUE THREAD

**Issue by IanVS** [paddle8/ember-plupload#6]
In the example in the readme, once a file is queued, a message like "Uploading 1 files. 50%" is displayed via `Uploading {{queue.length}} files. ({{queue.progress}}%)`

Is it possible to access the files within the queues to do something like display the filename or a thumbnail of the file?  Prior to uploading to the server?

**Comment by tim-evans** [comment]
Yes, both of these things are possible.

The file is passed into a route action, where you have access to the file name, size, etc. (See https://github.com/paddle8/ember-plupload/blob/master/addon/system/file.js)

You may get a thumbnail iff the browser supports the blob API. To do this, use snippets from https://github.com/paddle8/ember-plupload#custom-file-filters (the file in this instance is the plupload file object, accessed by `file.get('file')` in the route action).

Currently, the logic inside the demo template is looking at the queued count, but you can of course change that.

**Comment by IanVS** [comment]
Thanks, but I'm enough of a newbie that I'm still having difficulty.  The custom-file-filters example you references has a line:

```javascript
var image = new Image();
```

Which, as far as I can tell, is from [node-canvas](https://github.com/Automattic/node-canvas) (at least according to this [stackoverflow](http://stackoverflow.com/questions/9548074/nodejs-how-to-add-image-data-from-file-into-canvas))

Can you confirm that I'll need to install node-canvas (as well as its requirement, cairo) into my ember project to get blobs working correctly?  Or am I going down the wrong path?  So far, I'm trying the following, where `queueLogoFile` is the action in my `route.js` triggered by `pl-uploader`:

```javascript
queueLogo: function queueLogoFile(file){
  var deferred = Ember.RSVP.defer();
 
  var image = new Image();
  image.load(file.get('file').getSource());
  
  deferred.promise.then(function () {
    var blob = new Blob(image, { type: image.type });
    var blobUrl = window.URL.createObjectURL(blob);
    this.modelFor(this.routeName).set('logoBlobUrl', blobUrl);
  });
```

The end goal is to set the `logoBlobUrl` attribute of the route's model.  Am I way off here?  Any guidance you can give would be really useful.

**Comment by tim-evans** [comment]
Oh, that's an plupload image object. Oops!

**Comment by tim-evans** [comment]
@IanVS I added an example of reading the file to the dummy application in the addon. This addon isn't designed to handle those sort of things, but provides the ability to do these things if you want.

Cheers!

**Comment by IanVS** [comment]
That's awesome, thanks a bunch.  I know it's beyond the scope of what the addon is intended to do, but it's definitely a great feature that `ember-plupload` makes possible.  Thanks again for taking a noob by the hand and creating the example!

**Comment by tim-evans** [comment]
@IanVS I've amended the addon (and published) with the ability to get previews :+1:

In your route, call:

```javascript
export default Ember.Route.extend({
  actions: {
    upload: function (file) {
      file.read().then(function (dataURI) {});
    }
  }
});
```

**Comment by IanVS** [comment]
Thanks, that cleans it up considerably!
