### ISSUE TITLE
How to implement event callbacks

### ISSUE THREAD

**Issue by AdrienNguyenWorldline** [paddle8/ember-plupload#7]
How can we add callback methods on error events, such as file too big or forbidden extension (certains browsers only take extension filter as an advice and still allow other type selections) ?

Could you provide a sample ?

**Comment by tim-evans** [comment]
I believe the events should be passed via the file object. So when you call `upload`, it will fail with filters, etc.

If you want to add custom file filters, use https://github.com/paddle8/ember-plupload#custom-file-filters

The items you're asking for are available via the public API of the component. (`max-file-size` and `extensions`)
